### ISSUE TITLE
switchButton.R not found

### ISSUE THREAD

**Issue by mlist** [boutroslab/HTSvis#1]
When starting the app with ```HTSvis()``` I get the following error: 

```
Warning in file(filename, "r", encoding = encoding) :
  cannot open file './switchButton.R': No such file or directory
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
```

I noticed the file is called "SwitchButton.R" maybe it is just the different case of s that is causing the problem.

**Comment by cscheeder** [comment]
Hi,
 you're right there was a typo in the file name and I just fixed it. Thank you for the notice and please let me know if you have any further problems.
Christian
