### ISSUE TITLE
topTable Illustration Has Duplicated ID Variables Rows

### ISSUE THREAD

**Issue by DarioS** [boutroslab/HTSvis#2]
In the help pages of the Shiny application, an illustration of topTable.txt is provided. The first row and the last row contain the same well, annotation, and plate values. These three columns form a composite primary key so each row should have a distinct set of values.

**Comment by cscheeder** [comment]
Thank you for the notice @DarioS, I fixed it for the package version and the online app will be corrected within the next days.
